### ISSUE TITLE
clara enc encode does not supports passwords with "="

### ISSUE THREAD

**Issue by hmlth** [edf-hpc/clara#100]
They are striped when the file is read:
https://github.com/edf-hpc/clara/blob/master/clara/utils.py#L127

Since the scibiand-hpc-install-guide tells to use base64, this is a big issue.

**Comment by rezib** [comment]
PR #86 fixes this.

**Comment by ana** [comment]
Fixed in 33be78539d64629802525025860db91db101a2f9
