### ISSUE TITLE
Run "apt-get dist-upgrade" at the end of image creation

### ISSUE THREAD

**Issue by fmdm** [edf-hpc/clara#112]
All the repositories are not present when executing deboostrap, and upgrade of some packages can be present in calibre repositories.
To be sure to install theses updates, it is necessary to run "apt-get dist-upgrade" just before compressing the image.

**Comment by aurelien-git** [comment]
This part seems to be already present at line 255 of clara/plugins/clara_images.py with
`run_chroot(["chroot", work_dir, "apt-get", "dist-upgrade", "--yes", "--force-yes"])`
Can you please paste the log of that action or link me to the how to test it myself?

**Comment by rezib** [comment]
> This part seems to be already present at line 255 of clara/plugins/clara_images.py with
> `run_chroot(["chroot", work_dir, "apt-get", "dist-upgrade", "--yes", "--force-yes"])`
> Can you please paste the log of that action or link me to the how to test it myself?

True, I close it with invalid label.
