### ISSUE TITLE
enc: clara on debian>=9 should be able to decode files created on debian<=8

### ISSUE THREAD

**Issue by hmlth** [edf-hpc/clara#118]
OpenSSL changed its digest format for `enc(1)`. Files created on debian8 can only be decrypted with:

```
openssl enc -d -md md5 ....
```

**Comment by infocality** [comment]
The default digest was changed from MD5 to SHA256 in Openssl 1.1.0
Now the digest type is defined in config.ini instead of using the default digest of the operating system.   
sha256 is used in case of invalid or undefined digest type.
