### ISSUE TITLE
New feature to grab the last jenkins build and add it to repo

### ISSUE THREAD

**Issue by rezib** [edf-hpc/clara#57]
It would be great if clara have this feature:

```
# clara repo forgesync <repo> <pkg>
```

1/ it downloads the last successful build artefacts of `<pkg>` on jenkins
2/ it deletes the previous version of `<pkg>` in `<repo>`, if present
3/ it pastes the sources and binaries of `<pkg>` in `repo_src_dir` and `repo_bin_dir`
4/ it adds the new version of `<pkg>` in `<repo>`
5/ profit!

**Comment by mehdid** [comment]
I /think/ that we should define a workflow between repos, clusters and jenkins installation before implementing this feature.

**Comment by rezib** [comment]
You're right, a pkgs workflow must be defined, definitely.

This feature could work the same way on both clusters and forge server though, so that's not a real technical blocker from my standpoint.

**Comment by rezib** [comment]
:+1:
