### ISSUE TITLE
add support for default conf params

### ISSUE THREAD

**Issue by rezib** [edf-hpc/clara#91]
Clara currently requires that all configuration parameters are defined in the configuration file. This prevents from adding new configuration params and not messing up things on other installations, where default would be perfectly fine.

**Comment by mehdid** [comment]
Does 067931a7aaf168019cfd8062013c569738c292dc fixes what you are referring to? If it doesn't, can you please explain why?

**Comment by rezib** [comment]
Not totally as most parameters are still required in the configuration files.

A good way to fix it is to provide an hard-coded default configuration to configparser, eg. as well as Neos does: https://github.com/edf-hpc/neos/blob/master/neos/conf.py#L110

NB: This default configuration file could also be provided as a separate file in `/usr`
