### ISSUE TITLE
Support creating images in other places than /tmp

### ISSUE THREAD

**Issue by rezib** [edf-hpc/clara#92]
According to FHS, `/tmp` can be small. Therefore, this is not a safe place to build large diskless images.

It would be nice to add a configuration parameter to control where the image is actually build, eg. `/var/tmp`.

It probably depends on #91 as we do not want to change all current configurations where a default /tmp works well.

**Comment by rezib** [comment]
For information, this can be workaround with `TMIDIR` environment variable, thanks to Python [tempfile](https://docs.python.org/2/library/tempfile.html#tempfile.mkstemp) module:

```
TMPDIR=/var/tmp clara images create <image>
```

**Comment by mehdid** [comment]
My feeling is that this bug should be closed without modifications in the code. Do you agree?
